package packfarm;

import java.util.Random;

/** 
 * Represents the sensors that are going to be used in order to monitorize farm animals
 * @author Oihan
 * @version 1
 */
public class Sensor {
	private String id;
	
	/**
	 * Sensor class constructol. Initializes sensor id
	 * @param id sensor id
	 */
	public Sensor(String id) {
		this.id = id;
	}
	
	/**
	 * Returns the physiological values generated by collect() method
	 * @return a call to collect() method
	 * @throws CollectErrorException when it is not possible to return the values
	 */
	public PhysiologicalValues collectValues() throws CollectErrorException {
		return collect();
	}
	
	/**
	 * Simulates physiological values collection with potential failure
	 * @return the collected physiological values
	 * @throws CollectErrorException when it is not possible to return the values
	 */
	private PhysiologicalValues collect() throws CollectErrorException{
		Random r = new Random();
	    int heartRate = 0;
	    double temperature = 0.0;
	    int activity = 0;
	    heartRate = 60 + r.nextInt(20);
	    
	    temperature = 101.5 + r.nextDouble();
	    temperature = Double.parseDouble(String.format("%.2f", temperature).replace(',', '.'));
	    activity = r.nextInt(5)+1;  
	    
	    PhysiologicalValues phy = new PhysiologicalValues(heartRate, temperature, activity);
	    if (Math.random() >= 0.9) throw new CollectErrorException(phy.toString());
	    return phy;
	}
	
	/**
	 * Overwritten from Object superclass in order to return a propper String with the sensor id
	 */
	@Override
	public String toString() {
		return id;
	}

		
	// *--- Exceptions ---*
	
	/**
	 * Random error exception, used to learn exceptions handling (used in collect() method)
	 * @author Oihan
	 * @version 1
	 */
	@SuppressWarnings("serial")
	public class CollectErrorException extends Exception {
		/**
		 * CollectErrorException constructor. Calls to Exception superclass constructor and
		 * passes by parameter the exeption message
		 * @param s the message
		 */
		CollectErrorException(String s) {
			super(s);
		}
	}
}
